### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by hkhalidz** [stephencelis/SQLite.swift#394]
I get the following error when I try to build this using Carthage. I am running Xcode 7.2  and Swift 2.1. I also tried compiling the Xcode project directly from Xcode to no avail. 

```
Work/Carthage/Checkouts/SQLite.swift/SQLite/Core/Value.swift:36:5: error: expected declaration
Work/Carthage/Checkouts/SQLite.swift/SQLite/Typed/Expression.swift:27:5: error: expected declaration
Work/Carthage/Checkouts/SQLite.swift/SQLite/Helpers.swift:35:5: error: expected declaration
WorkCarthage/Checkouts/SQLite.swift/SQLite/Helpers.swift:93:111: error: expected initial value after '='
Work/Carthage/Checkouts/SQLite.swift/SQLite/Helpers.swift:93:122: error: expected ',' separator
Work/Carthage/Checkouts/SQLite.swift/SQLite/Helpers.swift:93:122: error: expected parameter type following ':'
Work/Carthage/Checkouts/SQLite.swift/SQLite/Helpers.swift:93:122: error: expected ',' separator
Work/Carthage/Checkouts/SQLite.swift/SQLite/Helpers.swift:95:2: error: expected ')' in parameter
Work/Carthage/Checkouts/SQLite.swift/SQLite/Helpers.swift:97:78: error: expected initial value after '='
Work/Carthage/Checkouts/SQLite.swift/SQLite/Helpers.swift:97:89: error: expected ',' separator
Work/Carthage/Checkouts/SQLite.swift/SQLite/Helpers.swift:97:89: error: expected parameter type following ':'
Work/Carthage/Checkouts/SQLite.swift/SQLite/Helpers.swift:97:89: error: expected ',' separator
Work/Carthage/Checkouts/SQLite.swift/SQLite/Helpers.swift:99:2: error: expected ')' in parameter
```

**Comment by ryanholden8** [comment]
@hkhalidz Xcode 7.3 is required to build SQLite 0.10 and above

**Comment by hkhalidz** [comment]
In that case, I think we need to mention that in the documentation. I already pushed a change to it.

**Comment by jakooistra** [comment]
I got these errors last night, but decided to update Xcode. Using Xcode 7.3.1 this morning, I was able to build with no errors, using version 0.10.1.

This issue can probably be closed.

**Comment by kumaresan-cgvak** [comment]
I Face the same issue and am in a situation, where i cannot update my xcode. So, is there any other previous version which will work in Xcode 7.2

**Comment by jberkel** [comment]
Only Xcode8.x is supported at the moment.
