### ISSUE TITLE
Xcode 12 Beta SQLite.swift Can't Build

### ISSUE THREAD

**Issue by RuoG** [stephencelis/SQLite.swift#1009]
> Issues are used to track bugs and feature requests.
> Need  help or have a general question? Ask on Stack Overflow (tag sqlite.swift).

## Build Information

- Include the SQLite.swift version, commit or branch experiencing the issue.
- Mention Xcode and OS X versions affected.
- How do do you integrate SQLite.swift in your project?
    - CocoaPods

## General guidelines

- Be as descriptive as possible.
- Provide as much information needed to _reliably reproduce_ the issue.
- Attach screenshots if possible.
- Better yet: attach GIFs or link to video.
- Even better: link to a sample project exhibiting the issue.

![image](https://user-images.githubusercontent.com/49544632/87237853-d7201d80-c42d-11ea-9618-cc459cfe2cf4.png)

![image](https://user-images.githubusercontent.com/49544632/87237855-db4c3b00-c42d-11ea-881d-47f2d5edbc9e.png)

**Comment by danl3v** [comment]
Haven't seen these issues, but made some fixes here: https://github.com/stephencelis/SQLite.swift/pull/1008

**Comment by volatilegg** [comment]
@RuoG I faced the same `Redefinition of ...` issue, deintegrate and reinstall pod work for me  

```
pod deintegrate
pod install
```

**Comment by RuoG** [comment]
> Haven't seen these issues, but made some fixes here: #1008

Thanks，this bug is fixed。

https://github.com/stephencelis/SQLite.swift/pull/1008/commits/385ce0c1b9870c712e712491caa528591988be3e

**Comment by RuoG** [comment]
![截屏2020-07-12 上午10 41 17](https://user-images.githubusercontent.com/49544632/87237801-ef436d00-c42c-11ea-9631-8be61bcfc1ee.png)
![截屏2020-07-12 上午10 41 03](https://user-images.githubusercontent.com/49544632/87237802-f10d3080-c42c-11ea-9bf0-944e98e2b76c.png)

**Comment by marain87** [comment]
I got the same problem with this. 

Last time I used this #986 to solve on Xcode 11.5 

pod 'SQLCipher', '= 4.2.0'
pod 'SQLite.swift/SQLCipher', '~> 0.12.2'

But it isn't working on Xcode 12 beta 2 now…

**Comment by danl3v** [comment]
Beta 4 should fix this issue

**Comment by fishunt** [comment]
> Beta 4 should fix this issue

hello, My Xcode Has been update to Beta4,But This issue still happen!

**Comment by Hung-Hsun** [comment]
Still has this issue with Xcode Beta5!

**Comment by andrei-moldovan-dev** [comment]
Same issue on Xcode 12.0 beta 6.

**Comment by EduardoIbarra** [comment]
Still happening on Xcode 12.0 beta 6 (12A8189n)

**Comment by mobinzk** [comment]
Same issue with Xcode 12 GM seed any solutions?

**Comment by docpitz** [comment]
I'm not sure, but maybe #1006 will help you

**Comment by Pulichev** [comment]
I have found a temporary solution.
Check https://github.com/stephencelis/SQLite.swift/pull/970

My podfile now:

```
pod 'SQLite.swift/standalone', :git => 'https://github.com/stephencelis/SQLite.swift', :branch => 'master'
pod 'sqlite3', '3.29.0'
```

So, u have to install version from master.

**Comment by chrisozenne** [comment]
Using **SQLCipher** w/ **Xcode 12 GM**, I ran into a couple of different issues:

- Error: "Ambiguous use of `SQLITE_DETERMINISTIC`".
- Error: "Could not build module 'SQLite3'" in `SQLiteObjc.h` when trying to `@import SQLite3;`
- Multiple errors regarding: "Redefinition of `sqlite_...`"

What resolved **all** of these issues for me was to change the import statement in `SQLiteObjc.h`:

From:
```objective-c
@import SQLite3;
```

To:
```objective-c
@import SQLCipher.sqlite3;
```

After making this change and performing a clean & build, all of my build errors have resolved.

**Comment by jyjblrd** [comment]
This cartfile works for me:
`github "stephencelis/SQLite.swift" "385ce0c1b9870c712e712491caa528591988be3e"`

**Comment by haithngn** [comment]
Hi guys, this [workaround](https://github.com/Carthage/Carthage/blob/master/Documentation/Xcode12Workaround.md) worked for Xcode 12.1 (12A7403)

**Comment by Ryamonster10** [comment]
Hello, Still not working on the offical Xcode 12.3 application with no mods. Getting the same error.

**Comment by Ryamonster10** [comment]
<img width="568" alt="Screen Shot 2020-12-28 at 11 59 27 AM" src="https://user-images.githubusercontent.com/45019531/103230724-271f6d80-4904-11eb-8e3e-bc3e797b640f.png">

**Comment by docpitz** [comment]
Here ist the mod: [https://github.com/docpitz/SQLite.swift](https://github.com/docpitz/SQLite.swift)

**Comment by Ryamonster10** [comment]
Thanks, I will try it out soon and let you know my results.

**Comment by NathanFallet** [comment]
Should be fixed by #1051 and #1053. We're going to release a new version soon.

**Comment by NathanFallet** [comment]
Should be fixed by #1051 and #1053. We're going to release a new version soon.
